### PR TITLE
Remove fastpath and unsafe variants

### PR DESCRIPTION
**Pull request by swenson**
The fastpath and unsafe variants rely on particular values for Go internals and a lot of unsafe assumptions about types, functions, strings, arrays, etc.

We are not committed to maintaining these dangerous code paths, so it is safer to remove them altogether, and rely on the "not unsafe" and slow paths.

This will make this package a bit slower, but also a much smaller dependency, since the fastpath generated code is extremely large.

### CODE REVIEW

**Review by kisunji — COMMENTED** [review]
Could yout point me towards which files remove unsafe?
My understanding is that fastpath and unsafe are controlled by build flags; I see the fastpath being disabled in `fast-path.not.go` but unsure where to look for the unsafe

**Comment by swenson** [comment]
@kisunji `helper_unsafe.go` is where most of the unsafe code is. https://github.com/hashicorp/go-msgpack/pull/14/files#diff-9891b7f524743080430997fca4d9f041448a1d128e309d11e3768c317ee8068fL23 (this line is an example of the things that strike me as making these code paths hard to maintain)

It's worth noting that fastpath and unsafe are the defaults, so if you include `go-msgpack` as a dependency, you get the fastpath and unsafe versions.

**Comment by kisunji** [comment]
Ah I see it now, thanks. Will your refactors make it difficult to pull more upstream changes? Might not be a huge cost in the end.

**Comment by swenson** [comment]
Yes, this will make it hard to pull in upstream changes.

Really, at this point, we have effectively diverged with upstream, and this fork should focus more on safely supporting the current msgpack (and JSON for Nomad) formats, and drop everything else.

If folks want to have the newer features and performance of the upstream package, then they should use the upstream package. :)

**Review by kisunji — APPROVED** [review]

**Pull request merged**
